version: '3.4'
services:
  db:
    image: programmerms/db-mysql-prova-pratica-pjc
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: provapjc
    ports:
      - "3306:3306"
    networks:
      - provapjc-network
  prova-pratica-pjc:
    image: programmerms/prova-pratica-pjc
    restart: always
    build: ./projeto
    working_dir: /projeto
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./projeto:/projeto
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - provapjc-network
networks:
     provapjc-network:
        driver: bridge